
name: Playwright Automation

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    name: Execute tests on machine
    runs-on: [self-hosted, Windows, X64]

    env:
      CI: "true"
      TEST_ENV: dev

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute automation script
        run: |
          & "C:\Program Files\Git\bin\bash.exe" ./run.sh
